spring:
  datasource:
    url: jdbc:h2:mem:crossfit;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true

jwt:
  issuer: crossfit-app
  secret: "change-this-secret-to-a-long-random-value"
  access-token-validity-seconds: 3600

server:
  port: 8080
